leftnav:
- identifier: 5f20559f-62ba-4468-ab5f-04523a572094
  name: Introductory Programming Courses
  pageRef: /external-resources/introductory-programming-courses_5f20559f-62ba-4468-ab5f-04523a572094
  weight: 10
- identifier: 894b5794-8b3d-403a-bac3-06bf8b6bcf9b
  name: Archived D-Space Course
  pageRef: /external-resources/archived-d-space-course_894b5794-8b3d-403a-bac3-06bf8b6bcf9b
  weight: 20
